### ISSUE TITLE
render code blocks as code blocks not h2's

### ISSUE THREAD

**Issue by rolfedh** [asciidoctor/kramdown-asciidoc#80]
When I run:
```
find ./ -name "*.md"  \
    -type f \
    -exec sh -c  \
    'kramdoc --format=GFM  \
    --output={}.adoc {}' \;
```
against `/docs` in a local clone of https://github.com/rolfedh/build, kramdown renders code blocks as h2's.

For example, line 71+ of `docs/build.md` input file looks like this:
```
[source,yaml]
----
apiVersion: build.dev/v1alpha1
kind: Build
metadata:
  name: buildpack-nodejs-build
spec:
  source:
    url: https://github.com/sclorg/nodejs-ex
    credentials:
      name: source-repository-credentials
----
```
And line 71+ of the build.md.adoc output file looks like this:
```
== [source,yaml]

apiVersion: build.dev/v1alpha1
kind: Build
metadata:
  name: buildpack-nodejs-build
spec:
  source:
    url: https://github.com/sclorg/nodejs-ex
    credentials:
      name: source-repository-credentials
----
```
